name: Model IA
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - exo11
  pull_request:
    branches:
      - exo11

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn matplotlib seaborn

      - name: Run model test
        run: |
          python train.py

      - name: Upload test reports as artifacts
        # if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: |
            metrics.txt
            feature_importance.png
            residuals.png