name: Flask application
on:
  push:
    branches:
      - exo10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask application
        id: flask-run
        run: |
          export FLASK_APP=app.py
          nohup flask run &

      - name: Wait for Flask to start
        run: sleep 10

      - name: Stop Flask application
        if: success()
        run: |
          pkill -f 'flask run'