name: Model IA
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - exo11
  pull_request:
    branches:
      - exo11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model test
        run: |
          python train.py
  
  display:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Test-Reports
          path: ./artifacts

      - name: Display images
        run: |
          echo "![Feature Importance](./artifacts/feature_importance.png)" >> $GITHUB_STEP_SUMMARY
          echo "![Residuals](./artifacts/residuals.png)" >> $GITHUB_STEP_SUMMARY

      - name: Display metrics
        run: |
          echo "### Metrics" >> $GITHUB_STEP_SUMMARY
          cat ./artifacts/metrics.txt >> $GITHUB_STEP_SUMMARY