name: GitHub Actions Dependencies
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: echo "==================== INSTALL REQUIREMENTS ===================="
      - run: pip install -r ${{ github.workspace }}/.github/workflows/requirements.txt
      - run: echo "======================================================"